#pragma once

enum class Event
{
	TEXT_RENDER,
	TEXTURE_RENDER,
	TRANSFORM_MOVED,
	TRANSFORM_SCALED,
	TRANSFORM_ROTATED,
	HEALTH_CHANGED,
	BURGER_DROPS,
	BURGER_DROPS_1_ENEMY,
	BURGER_DROPS_2_ENEMYS,
	BURGER_DROPS_3_ENEMYS,
	BURGER_DROPS_4_ENEMYS,
	BURGER_DROPS_5_ENEMYS,
	BURGER_DROPS_6_ENEMYS,
	HOTDOG_DIES,
	PICLE_DIES,
	EGG_DIES,
	GAME_WON
};