#pragma once

enum class Event
{
	COMPONENT_TEXT_RENDER,
	COMPONENT_TEXTURE_RENDER,
	COMPONENT_TRANSFORM_MOVED,
	COMPONENT_TRANSFORM_SCALED,
	COMPONENT_TRANSFORM_ROTATED,
	COMPONENT_HEALTH_CHANGED,
	COMPONENT_ENEMY_DIES,
	COMPONENT_BURGER_DROPS
};